wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1680098838.11116
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.9.13
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 64
